# Generated by Django 4.2.2 on 2023-07-05 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog/images_en/')),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio/images_en/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
