# Generated by Django 4.2.2 on 2023-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_post_en_projects_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='post_en',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projects_en',
            name='description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='projects_en',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
