# Generated by Django 4.2.2 on 2023-07-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_tecskills_alter_post_title_alter_post_en_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecskills',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='skills/images/'),
        ),
    ]
