# Generated by Django 4.2.2 on 2023-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_tecskills_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('vacante', models.CharField(max_length=100)),
                ('compañia', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
