# Generated by Django 4.2.2 on 2023-07-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contactdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='compañia',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contactdata',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactdata',
            old_name='mensaje',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactdata',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactdata',
            old_name='vacante',
            new_name='position',
        ),
    ]
