# Generated by Django 4.2.2 on 2023-07-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_compañia_contactdata_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=80)),
                ('image', models.ImageField(default='default/default.png', upload_to='skills/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProSkills_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=80)),
                ('image', models.ImageField(default='default/default.png', upload_to='skills/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='post_en',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='blog/images_en/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='projects_en',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='portfolio/images_en/'),
        ),
        migrations.AlterField(
            model_name='tecskills',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
