# Generated by Django 4.2.2 on 2023-07-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_proskills_proskills_en_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proskills',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='skills/images_pro/'),
        ),
        migrations.AlterField(
            model_name='proskills_en',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to='skills/images_pro_en/'),
        ),
    ]
