# Generated by Django 4.2.2 on 2023-07-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_proskills_image_alter_proskills_en_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proskills',
            name='text',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='proskills_en',
            name='text',
            field=models.CharField(max_length=120),
        ),
    ]
