# Generated by Django 4.2.2 on 2023-07-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_proskills_text_alter_proskills_en_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proskills',
            name='text',
        ),
        migrations.RemoveField(
            model_name='proskills_en',
            name='text',
        ),
        migrations.AlterField(
            model_name='proskills',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proskills_en',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
